# Generated by Django 5.0.7 on 2024-08-06 11:09

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_account_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان'),
        ),
    ]
